### PR TITLE
redirect notice works

### LINKED ISSUE #931: when users click on redirect links that will lead them out of the wizard, there should be a redirect notice modal

### PR DESCRIPTION
**Pull request by Tanya0609**
Summary to changes:
1. add redirect notice modal when user clicks on "Report an Issue" in the right side bar
2. add redirect notice modal when user clicks on "Visit our GitHub" in the right side bar
3. refactor privacy modal to redirect modal 
(will need to check dependency checker privacy modal still works, and check individual license link in view licenses modal still opens a modal, but they will look slightly different than the redirect notice modal)

Some minors changes:
1. view licenses button is black background 
2. hide view licenses button from right side bar in the summary page ( since it is duplicate)
3. changing few naming

Where to click those buttons 
redirect-trigger

**Expected:**
redirect-notice

closes #931 #934

### CODE REVIEW

**Comment by markAtMicrosoft** [comment]
Clicking on either GitHub or Feedback in right panel produces the same redirect message.  Always GitHub 
image

**Comment by markAtMicrosoft** [comment]
And goes to the same place... should bot github and feedback just go to the github code?

**Comment by markAtMicrosoft** [comment]
Inconsistency between dialogs.  Github/Feedback has a link to return to vscode.  Licenses requires me to click the X button.

**Comment by Tanya0609** [comment]
**Report an Issue** it should go to **GitHub issue** page and **Visit our GitHub** it should go to **GitHub code** page

Yes, there are different modals, so that they are slightly different. Only the ones redirect a MS website, they have a link to return to vscode. Others don't have this link, it depends on which website, it may have a privacy statement link.

**Review by markAtMicrosoft — COMMENTED** [review]
Inconsistency between dialogs. Github/Feedback has a link to return to vscode. Licenses requires me to click the X button.

**Review by markAtMicrosoft — COMMENTED** [review]
image
image
First one is GitHub, second is Feedback.  Both go to the same URL: https://github.com/Microsoft/WebTemplateStudio

**Comment by Tanya0609** [comment]
Great Catch! PR updated.

**Review by markAtMicrosoft — COMMENTED** [review]
You missed a spot.  After creating the web app, you have a link for feedback that does not have the leaving prompt.
image

**Review by markAtMicrosoft — COMMENTED** [review]
image
why is this different?

**Comment by Tanya0609** [comment]
add link to license redirect modal based on Mark's suggestion. Also, discussed with Mark, we won't add redirect modal for post generation, since if user clicks on Report an Issue and it opens a redirect modal, then user will lose post generation modal.

**Review by markAtMicrosoft — APPROVED** [review]

**Review by jasmingoh — APPROVED** [review]

**Review by streetcoder123 — APPROVED** [review]

**Pull request merged**
