### PR TITLE
Azure - Remove Functions completely from UI

### PR DESCRIPTION
**Pull request by jasmingoh**
With the new Azure page design, we decided to take Functions out of preview mode as well.

All the extension side code will remain in the code base, except for the top layer (i.e. the generationExperience)

### CODE REVIEW

**Comment by SahilTara** [comment]
So no more Azure functions? Might wanna adjust the wording since it seems like you are setting preview to false but that's not the case right? You seem to be removing functions entirely from the UI.

**Review by Tanya0609 — APPROVED** [review]
Functions is no longer show in the frontend!

**Review by Tanya0609 — CHANGES_REQUESTED** [review]
When I tried to generate a project with App Service and CosmosDB, it crushes at post generation modal

**Comment by jasmingoh** [comment]
@Tanya0609 it's fixed! please try to break it and see if there is other bugs

**Review by SahilTara — APPROVED** [review]

**Review by piotrmark — APPROVED** [review]

**Review by jcoc611-microsoft — APPROVED** [review]

**Review by jsondoo — APPROVED** [review]

**Review by Tanya0609 — APPROVED** [review]

**Pull request merged**
