### PR TITLE
Fixed Fonts on Mac

### LINKED ISSUE #1039: Fonts aren't consistent/ideal on Mac
Where: Privacy/Redirect Modal and Post generation Modal
Screen Shot 2019-08-07 at 8 33 02 PM
Screen Shot 2019-08-07 at 8 33 22 PM

### PR DESCRIPTION
**Pull request by SahilTara**
Fixed font consistency on Mac. Let me know if you wan't any changes in terms of font-weight. @xtinah-w 

### Licenses
image

### Post Gen Modal
image

### Redirect
image

### Licenses
image

### Post Gen Modal
image

### Redirect
image

closes #1039

### CODE REVIEW

**Review by jsondoo — DISMISSED** [review]
loooks good (on windows)

**Review by annielovesjs — DISMISSED** [review]
looks good on windows, could someone test on mac?

**Comment by SahilTara** [comment]
Those images are from mac

**Comment by xtinah-w** [comment]
I edited it from Jasmin's account and just checked the branch on windows/mac. I changed the font-size as well to be consistent with the rest of the system. Thanks Sahil for bringing this issue up! :)

**Review by xtinah-w — APPROVED** [review]

**Review by jsondoo — APPROVED** [review]

**Review by piotrmark — APPROVED** [review]

**Review by Tanya0609 — APPROVED** [review]

**Pull request merged**
