### PR TITLE
card color change 

### PR DESCRIPTION
**Pull request by annielovesjs**
Changes: 
- changed the card color so its not orange and unreadable on high contrast 

Before (on dark, light, and high contrast mode):
contrastDarkModeNone
contrasthighcontrastnone
contrastlighmodenone

After (on dark, light, and high contrast mode):
contrastdark
contrasthighcontrast
contrastlightcontrast

### CODE REVIEW

**Comment by SahilTara** [comment]
Can you show a before and after of the affected item if possible?

**Comment by jcoc611-microsoft** [comment]
> Can you show a before and after of the affected item if possible?

on both dark and light themes if possible :)

**Comment by annielovesjs** [comment]
@jcoc611-microsoft @SahilTara Yup! The images are up now

**Comment by jsondoo** [comment]
Should we also change the azure services card? it's still orange

**Comment by annielovesjs** [comment]
> Should we also change the azure services card? it's still orange

done!

**Review by jsondoo — APPROVED** [review]
great improvement 👍

**Review by SahilTara — APPROVED** [review]

**Review by streetcoder123 — APPROVED** [review]

**Review by jcoc611-microsoft — APPROVED** [review]
Great work!

**Pull request merged**
