### PR TITLE
Include CosmosDB conections when add CosmosDB Feature in all backend frameworks

### PR DESCRIPTION
**Pull request by dgomezc**
## PR checklist

- Quick summary of changes

Split CosmosDB templates in Node/Flask/Moleculer frameworks to allow connect with database when we add CosmosDB feature (without depending on the List page).

- Which issue does this PR relate to?
#1134

### CODE REVIEW

**Comment by dgomezc** [comment]
Hi @AndreMaz,

could you have a look at the changes for moleculer templates here?

**Comment by AndreMaz** [comment]
Hi @dgomezc  Sure thing. I'll test the templates and give you my feedback in a moment.

**Comment by AndreMaz** [comment]
@dgomezc tested over here and found a slight issue in CosmosDB SQL version. (Templates with MongoDB are generated correctly.)

`start-backend` in `./package.json` is missing `--env` option.
Currently:
```js
"start-backend": "moleculer-runner --repl --hot --config server/moleculer.config.js server/services",
```
Should be:
```js
"start-backend": "moleculer-runner --repl --hot --env --config server/moleculer.config.js server/services",
```

Also, `--envfile` param is missing in `start` in `./server/package.json`:
Currently:
```js
"start": "moleculer-runner services"
```
Should be:
```js
"start": "moleculer-runner --envfile ../.env services"
```

**Comment by AndreMaz** [comment]
@dgomezc tested again with the latest changes and everything is working properly :+1:

**Review by sibille — APPROVED** [review]

**Pull request merged**
