### PR TITLE
Changed 'Welcome' to 'New Project'

### PR DESCRIPTION
**Pull request by jasmingoh**
Resolving issue [#625](https://github.com/microsoft/WebTemplateStudio/issues/625)

Talked to Christina (designer on the team) about changing the "Welcome" text to "New Project". 

We looked at Windows Template Studio as reference, and found that they don't have a "Welcome" page, i.e. they start with the "Project Type" page. Before the Windows Template Studio extension pop up, the user is on a "New Project" window. Hence, we decided to make this change.

Here's the before and after:

Before:
BEFORE

After:
AFTER

### CODE REVIEW

**Comment by jcoc611-microsoft** [comment]
Do we also need to change `ROUTES.WELCOME` to `ROUTES.NEW_PROJECT`? What about `src\client\src\containers\Welcome` to `src\client\src\containers\NewProject`? Might be a bit confusing to someone new coming in to the codebase

**Comment by jasmingoh** [comment]
@jcoc611-microsoft Thanks for pointing that out! It make sense to change those filenames. I'll look around and see if there is any other relevant files.

**Comment by crutkas** [comment]
Did you mean to close this branch?

**Comment by jasmingoh** [comment]
I wanted to rename the branch because it did not make sense, but I didn't know it would close this one..

**Pull request closed without merging**
