### PR TITLE
add aria-labels to top nav bar links

### PR DESCRIPTION
**Pull request by annielovesjs**
Changes:
- added aria labels to top nav bar

How to Test with screen reader:
- go to settings -> ease of access -> narrator 
- turn narrator on
- build the extension and run it
- click on the tabs on top nav bar and you should hear "go to ___ page [link]" where [link] is added in by default

### CODE REVIEW

**Comment by SahilTara** [comment]
Let me know if this works, I'll approve code looks good. (Can't test this myself at the moment).

**Review by piotrmark — APPROVED** [review]

**Review by jsondoo — COMMENTED** [review]
It seems to work on browser but on extension it always says 'No item in view'

**Comment by annielovesjs** [comment]
> It seems to work on browser but on extension it always says 'No item in view'

I encounter that problem too even with the items that already have aria-label

I find that narrator is pretty inconsistent when you hover over items with aria-labels - sometimes it returns the value of the aria-label and sometimes it saids 'no item in view'

**Review by jsondoo — APPROVED** [review]

**Comment by jcoc611-microsoft** [comment]
> > It seems to work on browser but on extension it always says 'No item in view'
> 
> I encounter that problem too even with the items that already have aria-label

After a bit of research, I have found that [Windows Narrator is not good for accessibility.](https://github.com/microsoft/vscode/issues/10729)

Please try one of the following: NVDA, JAWS, WindowEyes, or ZoomText

**Review by jcoc611-microsoft — APPROVED** [review]

**Pull request merged**
