### PR TITLE
Accessibility: Top nav bar overlap fixed

### LINKED ISSUE #991: On some screens the "Create Your Web App in Seconds" is cut off by Nav
On the Welcome page the Create Your Web App in Seconds gets cut off by the nav bar due to screen scaling.
 

image

Screen size + Scaling
image

### PR DESCRIPTION
**Pull request by annielovesjs**
Accessibility task:
- Increase text size to 200%. - nothing should be overlapping 

Changes/How to test:
- top nav bar should not overlap the title when you zoom to 200% on the first page

closes #991

### CODE REVIEW

**Review by streetcoder123 — COMMENTED** [review]
The home page becomes like this when I zoom in

image

**Comment by annielovesjs** [comment]
> The home page becomes like this when I zoom in
> 
> image

It should be good now! Forgot to add an additional change I made when I was testing on the browser xD

**Review by jasmingoh — DISMISSED** [review]
Works!


I don't think people would zoom in this much and I'm not sure if this is an accessibility issue, but would it make more sense for the top nav bar to be on top of the footer?
image

**Comment by jsondoo** [comment]
looks great, overlap is fixed, but i think quick starts needs margin/padding
image

**Comment by annielovesjs** [comment]
> Works!
> 
> I don't think people would zoom in this much and I'm not sure if this is an accessibility issue, but would it make more sense for the top nav bar to be on top of the footer?
> image

We only have to consider up to 200% for accessibility :) so it is not an issue as of now

**Comment by annielovesjs** [comment]
> looks great, overlap is fixed, but i think quick starts needs margin/padding
> image

Good catch! I added the fix

**Review by jsondoo — APPROVED** [review]
very nice :D

**Review by SahilTara — APPROVED** [review]

**Review by Tanya0609 — APPROVED** [review]

**Comment by Tanya0609** [comment]
When it gets supper small, WebTS is overlaps with the step numbers. I think based on Annie's comment, this situation is not under consideration. Overall, great work!
Screen Shot 2019-08-08 at 10 57 13 PM

**Review by jcoc611-microsoft — APPROVED** [review]

**Pull request merged**
