### PR TITLE
Fixed Error Handling Bug for Specific "Untracked" Commands

### PR DESCRIPTION
**Pull request by trevorNgo**
Wrap function call to catch errors, leverage telemetry module _callWithTelemetryAndCatchHandleErrors_ to log in AppInsights and launch report an issue experience

Lint to follow standard Prettier

### CODE REVIEW

**Review by annielovesjs — COMMENTED** [review]
I ran the extension with your branch and I got this error when I tried to select the subscriptions from the dropdown - doesn't seem like it's retrieving information from azure properly. It's the same error with both the cosmosdb form and functions
AzureError

**Comment by trevorNgo** [comment]
> I ran the extension with your branch and I got this error when I tried to select the subscriptions from the dropdown - doesn't seem like it's retrieving information from azure properly. It's the same error with both the cosmosdb form and functions
> AzureError

Would be so curious to see the error stack (click the report an issue button)...

also, notice how little the logger actually helps... #658

**Comment by annielovesjs** [comment]
@trevorNgo hmm, I can't seem to replicate the error... It seems fine when I run it now

**Comment by SahilTara** [comment]
@annielovesjs could it have been a connectivity problem?

**Comment by annielovesjs** [comment]
@SahilTara it's probably likely since I can't seem to duplicate the error

**Comment by crutkas** [comment]
Does the error happen on other local branches / the nightly?

**Comment by annielovesjs** [comment]
@crutkas nope it's not a problem with the nightly branch either so it looks like it was just a connectivity problem on my end. I will close this issue since it cannot be replicated

**Review by annielovesjs — APPROVED** [review]

**Review by SahilTara — APPROVED** [review]

**Comment by Tanya0609** [comment]
@trevorNgo Hi same question as the other PR. How can I check if this PR? and what are the expected result? Or I just use the wizard to generate a template to see if it breaks anything?

**Review by jsondoo — APPROVED** [review]

**Review by jasmingoh — APPROVED** [review]
Code looks good. Set up a mock Application Insight (webts-local-test) for testing. 

"Report an issue" experience is launched, and events are logged in AppInsight.

**Pull request merged**
