### PR TITLE
Azure Form Update

### LINKED ISSUE #1073: Revise Azure Services Form for better readability + visual hierarchy
appServiceInstance

- [x] Increase padding between unrelated sections to break up visual hierarchy
- [x] Label caption should be smallest text with 80% opacity
- [x] App Service plan section should have removed heading

### PR DESCRIPTION
**Pull request by jsondoo**
closes #1073 

**Changes**
- All forms have 35px between sections and sublabels with 80% opacity and smaller font size
- Reordering CosmosDB form sections per #1079 
- string updates, clean up unused CSS and code

image
image

### CODE REVIEW

**Comment by annielovesjs** [comment]
Works well but I feel like the spacing seems a bit too big - maybe try 35px for the spacing between the sections? @xtinah-w what do you think?

**Review by annielovesjs — DISMISSED** [review]
stellar job

**Comment by jasmingoh** [comment]
> App Service Plan information only shows up if Create a new resource group is selected

App Service Plan information should always shows up cause we are creating a new one for them whether they want a new resource group or choose any existing one

**Review by piotrmark — APPROVED** [review]

**Review by Tanya0609 — APPROVED** [review]
Great work!

**Review by annielovesjs — APPROVED** [review]

**Review by streetcoder123 — APPROVED** [review]

**Pull request merged**
