### PR TITLE
Update yarn.lock

### PR DESCRIPTION
**Pull request by jsondoo**
Azure DevOps recommends that we run `npm audit fix` to update package versions.

Since we use yarn for our lock file, I generated a `package-lock.json`, ran the above command, then imported it as a `yarn.lock`

Please test for any breaking changes in the client

### CODE REVIEW

**Comment by jcoc611-microsoft** [comment]
Will approve once someone rebuilds and tests everything works as expected

**Comment by Tanya0609** [comment]
error-when-build

**Review by Tanya0609 — APPROVED** [review]

**Comment by jsondoo** [comment]
> I am trying to build on Windows, this error happens, but it also happens in dev branch as well, thus this should be fixed in a different PR. (This error doesn't exist on Mac).

I'm able to build on this branch and dev as well atm (on windows)

**Comment by Tanya0609** [comment]
Should we merge this PR after other PRs get merged?

**Comment by jsondoo** [comment]
discussed this with @Tanya0609

We will put this in once all the PRs from today are in, see if it breaks anything and removes warning on Azure DevOps. If not, we will just revert it

**Review by jcoc611-microsoft — APPROVED** [review]

**Review by jasmingoh — APPROVED** [review]

**Pull request merged**
