### PR TITLE
Change internal name to Angular from AngularJS

### PR DESCRIPTION
**Pull request by jsondoo**
Change internal name to Angular from AngularJS
Resolving follow-up on #599 @sibille 

To test you should run ./build and also repackage templates

### CODE REVIEW

**Review by SahilTara — COMMENTED** [review]
Will test this out later in the day, but it seems good at first glance. Will give an approval once I've ensured that it works (it most likely does but still have to test!).

**Comment by jsondoo** [comment]
Thanks @SahilTara, really appreciate the help

**Comment by SahilTara** [comment]
Yup just tested everything seems to be good 😄

**Review by SahilTara — APPROVED** [review]

**Review by streetcoder123 — APPROVED** [review]
This works Good 👍

**Pull request merged**
