### PR TITLE
Change azure page design + copy 

### PR DESCRIPTION
**Pull request by annielovesjs**
Changes:
- styling changes 
- made it more responsive
- changed text

How to test:
- Should look like this on normal screen (on extension): 
azurechanges

- should look like this on large screen (this is on localhost)
largesscreenazure

### CODE REVIEW

**Review by streetcoder123 — COMMENTED** [review]
The width of the right sidebar seems to increase a little bit as we go from pages page to the azure services page. Maybe that has something to do with the added scrollbar in the azure services page. Can we do something about it?

**Comment by markAtMicrosoft** [comment]
I thnk that subtle change in the width of the sidebar really needs to get resolved.  Either that or it's a bug and we need to see a link to the bug and commitment to resolve.

**Review by markAtMicrosoft — COMMENTED** [review]
I thnk that subtle change in the width of the sidebar really needs to get resolved. Either that or it's a bug and we need to see a link to the bug and commitment to resolve.  Unfortunately the screen shots make it look the same but it's not.
image
image

**Comment by annielovesjs** [comment]
@markAtMicrosoft @njindal239 it's actually a bug that's on the dev branch as well. I will log this issue and address it in a separate pr shortly

**Review by jasmingoh — APPROVED** [review]

**Review by streetcoder123 — APPROVED** [review]

**Review by xtinah-w — APPROVED** [review]

**Pull request merged**
