### PR TITLE
Add Build Route

### LINKED ISSUE #772: Add Build Route to Flask App to make it Production Ready
We need to add build Route to the flask routes so that it can render the complete front-end application along with all the static assets once the front-end application is built.
This step is essential in the deployment of the application.

### PR DESCRIPTION
**Pull request by streetcoder123**
Task: https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/28599

**Changes**
- This PR adds the route to serve the front-end application along with all its static assets once the application is production built.

Note: You need to install flask using `pip install flask`

**How to Check**
- **Check 1**
    - Create a Flask application (with any frontend) with all 4 pages selected.
    - Run `yarn install` on the application
    - Run `yarn build` on the application
    - Run `yarn start-backend` to run the backend
    - Now, go to 'localhost:3001' and try to work with the application. It should work appropriately.

- **Check 2**
    - Create a Flask application (with any frontend) with all 4 pages selected using Cosmos Mongo Database.
    - Install Python dependencies using `pip install python-dotenv` & `pip install pymongo`
    - Run `yarn install` on the application
    - Run `yarn build` on the application
    - Run `yarn start-backend` to run the backend
    - Now, go to 'localhost:3001' and try to work with the application. It should work appropriately.

- **Check 3**
    - Create a Flask application (with any frontend) with all 4 pages selected using Cosmos SQL Database.
    - Install Python dependencies using `pip install python-dotenv` & `pip install azure-cosmos`
    - Run `yarn install` on the application
    - Run `yarn build` on the application
    - Run `yarn start-backend` to run the backend
    - Now, go to 'localhost:3001' and try to work with the application. It should work appropriately.

closes #772

### CODE REVIEW

**Review by jasmingoh — APPROVED** [review]

**Comment by jsondoo** [comment]
For the coaches, you will also need to install python and run
```
pip install pymongo
pip install python-dotenv
pip install flask
```

**Review by jsondoo — APPROVED** [review]
good work 👍

**Review by SahilTara — APPROVED** [review]

**Comment by SahilTara** [comment]
@njindal239 do you think we should generate a requirements.txt as well?

**Comment by SahilTara** [comment]
Oh oops just saw an open issue regarding that never mind!

**Review by piotrmark — APPROVED** [review]

**Pull request merged**
