### PR TITLE
angular nav not using routerLink

### PR DESCRIPTION
**Pull request by Tanya0609**
This change is to address1 of the generated angular code feedback from GitHub Issue: #665
Task:https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/WTS%20Team/Intern%20GitHub/Y19-VS/03

In Angular <a> tag should use "routerLink" rather than "href"

**How to test:**
1. generate an angular project with at least any two pages are selected 
2. start your application (npm install, npm start)
3. click links under nav bar should redirect to corresponding page. **(expected)**

### CODE REVIEW

**Comment by SahilTara** [comment]
Do you think you (@Tanya0609)  or someone else could investigate a way to get the skip link working, in a different PR? Since it seems that its not working since before this PR as well. Think it has to do with href not being {{skipLinkPath}} or something of the sort. Even with that fix though with routerLinks it fails but with hrefs it passes, so there's probably a way to get it working with routerLinks. Just shouldn't have to deal with it if its already broken before this pr when this pr isn't targeted towards that.

**Review by SahilTara — APPROVED** [review]
Everything works as it should except skip links but it seems they didn't work before this PR either. Will have to investigate this

**Review by streetcoder123 — APPROVED** [review]

**Comment by Tanya0609** [comment]
@sahilTara I will log skip link as a different GitHub issue and fix it in next spring

**Comment by jsondoo** [comment]
> next spring

that sounds really late Tanya hhaha

**Review by jsondoo — APPROVED** [review]

**Comment by Tanya0609** [comment]
It is a typo LOL next sprint**

**Review by piotrmark — APPROVED** [review]

**Pull request merged**
