### PR TITLE
Cleaned up some code giving warnings

### PR DESCRIPTION
**Pull request by SahilTara**
This PR Addresses the following issues:
  - Some of the code was giving lots of "unused" warnings and such.
  - TopNavBar code was highlighted almost completely yellow. 
  - Weird glitch happening where a clicked disabled nav item would be highlighted blue for a split second.

### CODE REVIEW

**Comment by jasmingoh** [comment]
just curious, I still see that there are "unused" warnings, how did you decide which ones to fix in this PR?

**Comment by SahilTara** [comment]
> just curious, I still see that there are "unused" warnings, how did you decide which ones to fix in this PR?

I forgot some, I don't want to touch SelectOptions since @njindal239 is touching that file a decent amount.

**Comment by streetcoder123** [comment]
Thanks @SahilTara 
Moving code sometimes introduces a lot of unused warnings. I think this is another area we need to be careful about since it does not come up as error.
I shall also be looking into some of these as I touch files :)

**Review by streetcoder123 — APPROVED** [review]

**Review by annielovesjs — APPROVED** [review]
Thanks for the clean up :)

**Review by jsondoo — APPROVED** [review]

**Pull request merged**
