### PR TITLE
1595 update packages moleculer 

### PR DESCRIPTION
**Pull request by prupipho**
## PR checklist

- Quick summary of changes
update packages moleculer
- Which issue does this PR relate to?
#1595, #1656

### CODE REVIEW

**Comment by sibille** [comment]
Looks good to me!
@AndreMaz can you confirm moleculer setup and versions are correct after the project reorg from #1494 and the updates from this PR?

**Comment by AndreMaz** [comment]
Hey @sibille 

Regarding the versions, there should be no problem as there were no breaking changes in the latest releases.

Now regarding the project reorg, I've done a quick test (without CosmosDB) and it's looking good. I only see a tiny issue in the `package.json`

```json
"scripts": {
    "start-dev": "moleculer-runner services",
    "start": "moleculer-runner --repl --hot --config ./moleculer.config.js ./services",
  },
```
I'm assuming that `start-dev` is for development and `start` is for production. Right? If so then I would say that they should be swapped.

The `--repl` flag is used to enable the REPL terminal and the `--hot` is for hot reloading the services. Also, the `--config ./moleculer.config.js` is not necessary because `moleculer-runner` looks for the `moleculer.config.js` by default. The `--config` should be used when the configs are in a different file or dir. The `services` option indicates the dir where the services are located. So `moleculer-runner` will look at that dir and load all the files that have the following naming scheme: `<something>.service.js`

Having said that, I think that this is how things should look
```json
  "scripts": {
    "start-dev": "moleculer-runner --repl --hot services",
    "start": "moleculer-runner services"
  },
```

**Comment by sibille** [comment]
Thanks @AndreMaz. you're right! 
start-dev is for starting the backend in development, so according to the parameters you explained switching makes sense. I've adapted the task.json and readme.md in this PR too to fix this

**Comment by AndreMaz** [comment]
@sibille I didn't test the cosmosDB template but as far as I remember there was an `.env` file with password for the DB.
For loading the env vars you have 2 options:
```bash
# Load the default .env file from current directory
moleculer-runner --env services

# Load the specified .my-env file
moleculer-runner --envfile .my-env services
```

**Comment by sibille** [comment]
That's correct. Thanks for the info! I'll test and adjust the compositions for cosmos db.

**Comment by sibille** [comment]
Done, with Cosmos DB configuration is:
```
    "start-dev": "moleculer-runner --repl --hot --env services",
    "start": "moleculer-runner --envfile ./.env services",
```

**Review by sibille — APPROVED** [review]

**Pull request merged**
