### PR TITLE
Vue Functions Composition

### PR DESCRIPTION
**Pull request by SahilTara**
Summary of changes:
Implements the functions merging for vue. Selecting Azure functions with vue selected will now add an excerpt in the read me about azure functions. Mimics behavior of React+Angular.

Should be reviewed after #647

Just hit f5 and launch webts then hit generate! Dlls are in for windows and mac!
Related issues:
#199

### CODE REVIEW

**Comment by jcoc611-microsoft** [comment]
Despite the name, this has a bunch of compositions for Vue other than Azure Functions right? Still trying to understand the whole structure of the code

Edit: Closed by accident

**Comment by SahilTara** [comment]
Ah this PR shouldn't be reviewed yet. No its just for azure functions actually. Honestly I feel like this entire template should be in its own location now that you mention it.

**Comment by SahilTara** [comment]
I've done the same for angular + react as well so I should probably abstract it out into its own composition. Thanks!

**Comment by jcoc611-microsoft** [comment]
> Ah this PR shouldn't be reviewed yet. No its just for azure functions actually. Honestly I feel like this entire template should be in its own location now that you mention it.

Now that I think about it, do you think you could merge all the Vue-related stuff into a single PR? I think it would greatly help us on our end with reviewing the changes

**Comment by SahilTara** [comment]
Oh really? I split it all up because I thought that would make reviewing and such a lot easier. Will do so.

**Comment by SahilTara** [comment]
PR might be a bit big though.

**Comment by SahilTara** [comment]
Closed in favour of #676

**Pull request closed without merging**
