### PR TITLE
angular README fix

### PR DESCRIPTION
**Pull request by Tanya0609**
This PR is to fix one of the feedback given by Angular expert, here is the source:
https://github.com/Tanya0609/angular/pull/1/files

How to test this PR:
1. build your extension (no need to package templates anymore)
2. generate an angular templates 
3. check the README file in the generated templates

### CODE REVIEW

**Comment by SahilTara** [comment]
Do you need to package templates? If so merge dev, since it shouldn't be the case anymore.

**Comment by Tanya0609** [comment]
Because it made change under templates, it should do package, correct me if I am wrong

**Comment by SahilTara** [comment]
Well this was the case but I recently made a PR which got merged, which removed the packaging step to improve your development cycle. (#639)

**Review by SahilTara — APPROVED** [review]
Changes successfully made, 
image

**Review by jsondoo — APPROVED** [review]

**Review by annielovesjs — APPROVED** [review]

**Review by piotrmark — APPROVED** [review]

**Pull request merged**
