### PR TITLE
Abstract 'concurrently dependency' into fullStack template

### LINKED ISSUE #735: Abstract 'Concurrently' Dependency to FullStack Application template
'Concurrently' Dependency in the dev Depedendencies of back-end frameworks should be abstracted to the Full Stack Application template file
The reason is we need this dev dependency only if we are using Full Stack Application. It is not required for independent front-end and back-end applications.

### PR DESCRIPTION
**Pull request by streetcoder123**
Task: https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/28853

**Changes**
Currently all the backend frameworks insert `concurrently` as a dev dependency into the full stack application. However, this dependency is only needed for a full stack application and not for an independent frontend/backend application.
Hence, it makes more sense to have this dependency in the Full Stack Application template rather than individual backend templates.

closes #735

### CODE REVIEW

**Review by piotrmark — APPROVED** [review]

**Review by jsondoo — COMMENTED** [review]
It compiles fine for me but I'm getting some errors with both node and flask

```
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] BrowserslistError: Unknown browser query `android all`
[0] Compiled successfully!
```

Also some errors when I add list item or go to MasterDetail

**Comment by jsondoo** [comment]
@njindal239 Actually nvmd I think this is a separate issue https://github.com/microsoft/WebTemplateStudio/issues/752

**Review by jsondoo — APPROVED** [review]

**Review by jcoc611-microsoft — APPROVED** [review]

**Comment by jcoc611-microsoft** [comment]
I would like to see post action `CB387AC0-16D0-4E07-B41A-F1EA616A7CA9` be documented somewhere. Probably on CoreTS. Defined [here](https://github.com/microsoft/CoreTemplateStudio/blob/dev/code/src/CoreTemplateStudio/CoreTemplateStudio.Core/PostActions/Catalog/AddJsonDictionaryItem/AddJsonDictionaryItemPostAction.cs).

**Comment by streetcoder123** [comment]
@jcoc611-microsoft Do you have a suggestion where could this be documented?

**Comment by SahilTara** [comment]
@njindal239 CoreTS Wiki. While you're at it might as well do the other post actions as well.

**Pull request merged**
