### PR TITLE
Update regex for node version required

### PR DESCRIPTION
**Pull request by jasmingoh**
This PR is to address feedback we got about the dependency checker. Some people have Node version 12 installed, but they were still getting this warning (which is confusing):
image

Also, node version 12 will be active soon:
image

The regex is updated to match all node version above 10.15.

### CODE REVIEW

**Review by streetcoder123 — DISMISSED** [review]
This won't break until Node version 20 comes out lol

**Comment by jasmingoh** [comment]
> This won't break until Node version 20 comes out lol

it will be years from now lol

**Comment by jcoc611-microsoft** [comment]
Since basically all dependencies would use semantic versioning, I think it would be better to use regex to extract the semantic version and then use [semver comparison](https://github.com/npm/node-semver) to test whether minimum version is met.

```javascript
const semver = require('semver');
const NODE_REGEX = RegExp('v(.+)')
const NODE_REQUIREMENT = '>=10.15.x';

// ...
let nodeVerison = 'v12.34.56'; // from node --version
let nodeSemver = nodeVersion.match(NODE_REGEX)[1];
let nodeMatches = semver.satisfies(nodeSemver, NODE_REQUIREMENT);
```

The current function is a bit more complex but has more edge cases that are not met.

**Review by SahilTara — APPROVED** [review]
Ayy added semver 😄 Nice!

**Review by streetcoder123 — APPROVED** [review]

**Review by jcoc611-microsoft — APPROVED** [review]
Nice!

**Pull request merged**
