### PR TITLE
New flask logo

### LINKED ISSUE #733: Flask icon is very difficult to see
In dark mode the current flask icon is very difficult to see.

image

One possible fix is having a light variant of the icon, and swapping to it when the theme is dark enough.

### PR DESCRIPTION
**Pull request by jsondoo**
closes #733

image
image

### CODE REVIEW

**Review by jasmingoh — DISMISSED** [review]

**Comment by jcoc611-microsoft** [comment]
Does this need a special approval as it is a new image asset?

**Comment by jsondoo** [comment]
@jcoc611-microsoft yea, we are getting it approved

**Comment by jcoc611-microsoft** [comment]
> @jcoc611-microsoft yea, we are getting it approved

Okay, I will approve this one once that comes in

**Comment by jsondoo** [comment]
Still waiting on approval...

**Review by piotrmark — APPROVED** [review]

**Comment by jsondoo** [comment]
approved now

**Review by jasmingoh — APPROVED** [review]

**Review by trevorNgo — APPROVED** [review]
this is sweet

**Review by streetcoder123 — APPROVED** [review]

**Pull request merged**
