### PR TITLE
Azure forms sequential navigation

### PR DESCRIPTION
**Pull request by piotrmark**
Before:
- All fields enabled when Subscription selected
After:
- Fields enabled sequentially when previous field is not empty

How to test:
- Open all Azure services forms

image

### CODE REVIEW

**Comment by piotrmark** [comment]
BTW, the Azure forms code would need some love and refactoring ;)

**Review by jcoc611-microsoft — APPROVED** [review]

**Review by SahilTara — APPROVED** [review]

**Review by streetcoder123 — COMMENTED** [review]
@piotrmark Both `Location` and `Number of Functions` become activated once the `App Name` is selected. Is it desired or has it been missed out?

Update: `Number of Functions` is actually always enabled

**Comment by piotrmark** [comment]
> @piotrmark Both `Location` and `Number of Functions` become activated once the `App Name` is selected. Is it desired or has it been missed out?
> 
> Update: `Number of Functions` is actually always enabled

Yes, it was always enabled before, so I left it always enabled.
However I'm not sure if this this intended behavior. @xtinah-w?

**Review by jsondoo — APPROVED** [review]

**Comment by jsondoo** [comment]
From what I remember number of functions was always enabled from the start so it was left untouched but it probably makes more sense to disable it?

**Comment by xtinah-w** [comment]
Yeah, it would be great if we can disable it! This was a UX decision made from the previous cohort.

**Comment by xtinah-w** [comment]
Thank you, Piotr, for doing this! We just got feedback from Redmond for the Azure forms so we actually have to change the UX for this now :'( 

We just want to disable the entire form until they fill out subscription because we'll be pre-filling the project name for them and it's weird to have a pre-filled name when the fields are currently disabled.

Thank you for the work!!

**Comment by jsondoo** [comment]
Closing this PR - after our discussion, we will be prefilling some fields so disabling won't make as much sense anymore

Thank you @piotrmark for your beautiful work :)

**Pull request closed without merging**
